name: Braket
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip:
      - botocore==1.29.65
      - awscli==1.27.65
      - boto3==1.26.64
      - amazon-braket-default-simulator==1.15.0
      - amazon-braket-pennylane-plugin==1.15.1
      - amazon-braket-schemas==1.17.0
      # - amazon-braket-sdk==1.39.0
      - "amazon-braket-sdk @ git+https://github.com/aws/amazon-braket-sdk-python@arbitrary-angle-ms"
      - amazon-braket-algorithm-library==1.3.2
      - cvxpy==1.3.1
      - dask==2023.1.1
      - ecos==2.0.12
      - ipykernel==6.21.1
      - jax==0.4.2
      - jinja2==3.1.2
      - keras==2.12.0
      - markupsafe==2.1.2
      - matplotlib==3.6.3
      - mypy-extensions==0.4.3
      - openfermion==1.5.1
      - openfermionpyscf==0.5
      - oqpy==0.1.1
      - numpy==1.23.5
      - pandas==2.0.0
      - pennylane==0.30.0
      - PennyLane-Lightning==0.30.0
      - qiskit-aer==0.12.0
      - qiskit_braket_provider==0.0.4
      - qiskit-terra==0.23.3
      - scipy==1.9.3
