name: Braket
channels:
  - psi4
  - conda-forge
  - defaults
dependencies:
  - conda-pack=0.6.0
  - colorama=0.4.3
  - decorator=4.4.0
  - idna=2.10
  - ipython_genutils=0.2.0
  - ipykernel=5.3.4
  - markupsafe=2.1.1
  - matplotlib=3.2.2
  - networkx=2.4
  - numpy=1.21.6
  - nbconvert=6.5.4
  - openbabel=3.1.1
  - pandas=1.1.4
  - pip
  - protobuf=3.12.4
  - psi4=1.3.2
  - pydantic=1.9.0
  - python=3.8
  - python-dateutil=2.8.2
  - rsa=4.4.1
  - scipy=1.5.2
  - six=1.15.0
  - pip:
      - botocore==1.25.7
      - awscli==1.23.7
      - boto3==1.22.7
      - amazon-braket-default-simulator==1.11.5
      - amazon-braket-pennylane-plugin==1.11.2
      - amazon-braket-schemas==1.14.1
      - amazon-braket-sdk==1.35.5
      - amazon-braket-strawberryfields-plugin==1.0.3
      - amazon-braket-algorithm-library==1.1.3
      - cvxpy==1.1.17
      - dask==2.30.0
      - ecos==2.0.7.post1
      - jax==0.2.21
      - jinja2==3.1.2
      - keras==2.7.0
      - mypy-extensions==0.4.3
      - openfermion==1.0.0
      - openfermionpyscf==0.5
      - pennylane==0.27.0
      - PennyLane-Lightning==0.27.0
      - s3transfer==0.5.0
      - strawberryfields==0.23.0
      - tensorflow==2.7.0
      - torch==1.9.1
